### ISSUE TITLE
VPN glean script generated empty files [intermittently]

### ISSUE THREAD

**Issue by fvalenduc** [mozilla-mobile/mozilla-vpn-client#5443]
Building the current version gives the following error:

/usr/src/mozilla-vpn-client/src/apps/vpn/addons/addonmessage.cpp: In member function 'void AddonMessage::updateMessageState(MessageState)':
/usr/src/mozilla-vpn-client/src/apps/vpn/addons/addonmessage.cpp:116:3: error: 'mozilla' has not been declared
  116 |   mozilla::glean::sample::addon_message_state_changed.record(
      |   ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/addons/addonmessage.cpp:117:7: error: 'mozilla' has not been declared
  117 |       mozilla::glean::sample::AddonMessageStateChangedExtra{
      |       ^~~~~~~
make[2]: *** [src/CMakeFiles/mozillavpn.dir/build.make:1282: src/CMakeFiles/mozillavpn.dir/apps/vpn/addons/addonmessage.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp: In member function 'void AuthenticationInApp::setState(State, AuthenticationInAppSession*)':
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp:62:7: error: 'mozilla' has not been declared
   62 |       mozilla::glean::sample::authentication_inapp_step.record(
      |       ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp:63:11: error: 'mozilla' has not been declared
   63 |           mozilla::glean::sample::AuthenticationInappStepExtra{
      |           ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp:71:7: error: 'mozilla' has not been declared
   71 |       mozilla::glean::sample::authentication_acnt_del_step.record(
      |       ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp:72:11: error: 'mozilla' has not been declared
   72 |           mozilla::glean::sample::AuthenticationAcntDelStepExtra{
      |           ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp:80:7: error: 'mozilla' has not been declared
   80 |       mozilla::glean::sample::authentication_sub_manage_step.record(
      |       ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp:81:11: error: 'mozilla' has not been declared
   81 |           mozilla::glean::sample::AuthenticationSubManageStepExtra{
      |           ^~~~~~~
make[2]: *** [src/CMakeFiles/mozillavpn.dir/build.make:1506: src/CMakeFiles/mozillavpn.dir/apps/vpn/authenticationinapp/authenticationinapp.cpp.o] Error 1
/usr/src/mozilla-vpn-client/src/apps/vpn/addons/addon.cpp: In member function 'void Addon::updateAddonState(State)':
/usr/src/mozilla-vpn-client/src/apps/vpn/addons/addon.cpp:435:3: error: 'mozilla' has not been declared
  435 |   mozilla::glean::sample::addon_state_changed.record(

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-3665)

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

This compilation issue is generated by the glean python script that, sometimes, generates empty files.

**Comment by fvalenduc** [comment]
Thanks for the explanation, but is there a way to avoid the problem ?

**Comment by data-sync-user** [comment]
➤ Andrea Marchesini commented:

I run this: `rm -rf src/apps/vpn/glean/generated`

**Comment by fvalenduc** [comment]
Removing this directory indeed solved the problem.

Thanks for your help.

**Comment by fvalenduc** [comment]
In fact, this occurs very often if you switch between branches. If I first compile the main branch after an initial clone, it works correctly. But if then switch to the release-2.13.0, I get the error, and removing  src/apps/vpn/glean/generated does not help. In order to compile the 2.13.0 branch successfully, I have to completely erase the git tree and switch immediately to the 2.13.0 branch to compile it.

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

Hi folks, this was due to a change in structure of the project. When we first implemented the vpnglean module we were putting the generated files in the source folder. That was changed and we now put the generated files in the build folder. When you move to an updated branch, you will get errors in these leftover generated files in the source folder. I think there is no action to take here though, so I’ll close this ticket.

**Comment by fvalenduc** [comment]
So how can I avoid the problem ? As I said,  removing src/apps/vpn/glean/generated does not help when switching between branches. Which files should I then delete?

François Valenduc

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

I’m sorry François, I did not process that you were experiencing the issue even after deleting the folder. It is likely something else in that case, would you mind sharing you logs so I can help asses the issue?

**Comment by fvalenduc** [comment]
This is the error I get if I compile the 2.13.0 branch after having compiled the main branch:

[ 80%] Building CXX object src/CMakeFiles/mozillavpn.dir/apps/vpn/models/subscriptiondata.cpp.o
/usr/src/mozilla-vpn-client/src/apps/vpn/addons/addonmessage.cpp: In member function 'void AddonMessage::updateMessageState(MessageState)':
/usr/src/mozilla-vpn-client/src/apps/vpn/addons/addonmessage.cpp:116:3: error: 'mozilla' has not been declared
  116 |   mozilla::glean::sample::addon_message_state_changed.record(
      |   ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/addons/addonmessage.cpp:117:7: error: 'mozilla' has not been declared
  117 |       mozilla::glean::sample::AddonMessageStateChangedExtra{
      |       ^~~~~~~
gmake[2]: *** [src/CMakeFiles/mozillavpn.dir/build.make:1268: src/CMakeFiles/mozillavpn.dir/apps/vpn/addons/addonmessage.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp: In member function 'void AuthenticationInApp::setState(State, AuthenticationInAppSession*)':
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp:62:7: error: 'mozilla' has not been declared
   62 |       mozilla::glean::sample::authentication_inapp_step.record(
      |       ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp:63:11: error: 'mozilla' has not been declared
   63 |           mozilla::glean::sample::AuthenticationInappStepExtra{
      |           ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp:71:7: error: 'mozilla' has not been declared
   71 |       mozilla::glean::sample::authentication_acnt_del_step.record(
      |       ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp:72:11: error: 'mozilla' has not been declared
   72 |           mozilla::glean::sample::AuthenticationAcntDelStepExtra{
      |           ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp:80:7: error: 'mozilla' has not been declared
   80 |       mozilla::glean::sample::authentication_sub_manage_step.record(
      |       ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinapp.cpp:81:11: error: 'mozilla' has not been declared
   81 |           mozilla::glean::sample::AuthenticationSubManageStepExtra{
      |           ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/connectionhealth.cpp: In member function 'void ConnectionHealth::setStability(ConnectionStability)':
/usr/src/mozilla-vpn-client/src/apps/vpn/connectionhealth.cpp:139:5: error: 'mozilla' has not been declared
  139 |     mozilla::glean::sample::connection_health_unstable.record();
      |     ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/connectionhealth.cpp:143:5: error: 'mozilla' has not been declared
  143 |     mozilla::glean::sample::connection_health_no_signal.record();
      |     ^~~~~~~
gmake[2]: *** [src/CMakeFiles/mozillavpn.dir/build.make:1996: src/CMakeFiles/mozillavpn.dir/apps/vpn/connectionhealth.cpp.o] Error 1
gmake[2]: *** [src/CMakeFiles/mozillavpn.dir/build.make:1492: src/CMakeFiles/mozillavpn.dir/apps/vpn/authenticationinapp/authenticationinapp.cpp.o] Error 1
/usr/src/mozilla-vpn-client/src/apps/vpn/errorhandler.cpp: In member function 'void ErrorHandler::errorHandle(ErrorType, const QString&, const QString&, int)':
/usr/src/mozilla-vpn-client/src/apps/vpn/errorhandler.cpp:238:3: error: 'mozilla' has not been declared
  238 |   mozilla::glean::sample::ErrorAlertShownExtra extras;
      |   ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/errorhandler.cpp:242:5: error: 'extras' was not declared in this scope
  242 |     extras._task = taskName;
      |     ^~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/errorhandler.cpp:247:5: error: 'extras' was not declared in this scope
  247 |     extras._filename = fileName;
      |     ^~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/errorhandler.cpp:252:5: error: 'extras' was not declared in this scope
  252 |     extras._linenumber = lineNumber;
      |     ^~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/errorhandler.cpp:255:3: error: 'mozilla' has not been declared
  255 |   mozilla::glean::sample::error_alert_shown.record(extras);
      |   ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/errorhandler.cpp:255:52: error: 'extras' was not declared in this scope
  255 |   mozilla::glean::sample::error_alert_shown.record(extras);
      |                                                    ^~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/errorhandler.cpp:261:7: error: 'mozilla' has not been declared
  261 |       mozilla::glean::sample::authentication_failure_by_geo.record();
      |       ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/errorhandler.cpp:264:7: error: 'mozilla' has not been declared
  264 |       mozilla::glean::sample::authentication_failure.record();
      |       ^~~~~~~
gmake[2]: *** [src/CMakeFiles/mozillavpn.dir/build.make:2052: src/CMakeFiles/mozillavpn.dir/apps/vpn/errorhandler.cpp.o] Error 1
/usr/src/mozilla-vpn-client/src/apps/vpn/addons/addon.cpp: In member function 'void Addon::updateAddonState(State)':
/usr/src/mozilla-vpn-client/src/apps/vpn/addons/addon.cpp:435:3: error: 'mozilla' has not been declared
  435 |   mozilla::glean::sample::addon_state_changed.record(
      |   ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/addons/addon.cpp:436:7: error: 'mozilla' has not been declared
  436 |       mozilla::glean::sample::AddonStateChangedExtra{
      |       ^~~~~~~
gmake[2]: *** [src/CMakeFiles/mozillavpn.dir/build.make:1212: src/CMakeFiles/mozillavpn.dir/apps/vpn/addons/addon.cpp.o] Error 1
/usr/src/mozilla-vpn-client/src/apps/vpn/commands/commandui.cpp: In lambda function:
/usr/src/mozilla-vpn-client/src/apps/vpn/commands/commandui.cpp:246:7: error: 'mozilla' has not been declared
  246 |       mozilla::glean::sample::update_step.record(
      |       ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/commands/commandui.cpp:247:11: error: 'mozilla' has not been declared
  247 |           mozilla::glean::sample::UpdateStepExtra{
      |           ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/commands/commandui.cpp: In lambda function:
/usr/src/mozilla-vpn-client/src/apps/vpn/commands/commandui.cpp:553:26: error: '__DONOTUSE__GleanPings' has not been declared
  553 |           QObject* obj = __DONOTUSE__GleanPings::instance();
      |                          ^~~~~~~~~~~~~~~~~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/commands/commandui.cpp: In lambda function:
/usr/src/mozilla-vpn-client/src/apps/vpn/commands/commandui.cpp:560:26: error: '__DONOTUSE__GleanMetrics' has not been declared
  560 |           QObject* obj = __DONOTUSE__GleanMetrics::instance();
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/commands/commandui.cpp: In lambda function:
/usr/src/mozilla-vpn-client/src/apps/vpn/commands/commandui.cpp:571:7: error: 'mozilla' has not been declared
  571 |       mozilla::glean_pings::Main.submit();
      |       ^~~~~~~
gmake[2]: *** [src/CMakeFiles/mozillavpn.dir/build.make:1814: src/CMakeFiles/mozillavpn.dir/apps/vpn/commands/commandui.cpp.o] Error 1
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinappsession.cpp: In member function 'void AuthenticationInAppSession::deleteAccount()':
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinappsession.cpp:574:3: error: 'mozilla' has not been declared
  574 |   mozilla::glean::sample::delete_account_clicked.record();
      |   ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinappsession.cpp: In member function 'void AuthenticationInAppSession::processErrorObject(const QJsonObject&)':
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinappsession.cpp:756:7: error: 'mozilla' has not been declared
  756 |       mozilla::glean::sample::authentication_inapp_error.record(
      |       ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinappsession.cpp:757:11: error: 'mozilla' has not been declared
  757 |           mozilla::glean::sample::AuthenticationInappErrorExtra{
      |           ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinappsession.cpp:790:7: error: 'mozilla' has not been declared
  790 |       mozilla::glean::sample::authentication_inapp_error.record(
      |       ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinappsession.cpp:791:11: error: 'mozilla' has not been declared
  791 |           mozilla::glean::sample::AuthenticationInappErrorExtra{
      |           ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinappsession.cpp:962:7: error: 'mozilla' has not been declared
  962 |       mozilla::glean::sample::authentication_inapp_error.record(
      |       ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/authenticationinapp/authenticationinappsession.cpp:963:11: error: 'mozilla' has not been declared
  963 |           mozilla::glean::sample::AuthenticationInappErrorExtra{
      |           ^~~~~~~
gmake[2]: *** [src/CMakeFiles/mozillavpn.dir/build.make:1520: src/CMakeFiles/mozillavpn.dir/apps/vpn/authenticationinapp/authenticationinappsession.cpp.o] Error 1
/usr/src/mozilla-vpn-client/src/apps/vpn/models/subscriptiondata.cpp: In member function 'bool SubscriptionData::fromJsonInternal(const QByteArray&)':
/usr/src/mozilla-vpn-client/src/apps/vpn/models/subscriptiondata.cpp:136:5: error: 'mozilla' has not been declared
  136 |     mozilla::glean::sample::unhandled_sub_plan_interval.record(
      |     ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/models/subscriptiondata.cpp:137:9: error: 'mozilla' has not been declared
  137 |         mozilla::glean::sample::UnhandledSubPlanIntervalExtra{
      |         ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/models/subscriptiondata.cpp:167:7: error: 'mozilla' has not been declared
  167 |       mozilla::glean::sample::unhandled_sub_plan_interval.record(
      |       ^~~~~~~
/usr/src/mozilla-vpn-client/src/apps/vpn/models/subscriptiondata.cpp:168:11: error: 'mozilla' has not been declared
  168 |           mozilla::glean::sample::UnhandledSubPlanIntervalExtra{
      |           ^~~~~~~
gmake[2]: *** [src/CMakeFiles/mozillavpn.dir/build.make:2500: src/CMakeFiles/mozillavpn.dir/apps/vpn/models/subscriptiondata.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1126: src/CMakeFiles/mozillavpn.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

The problem doesn't occur if I clone the git tree and then switch immediately to the 2.13.0 branch without compiling the main branch . I delete the build folder and src/apps/vpn/glean/generated before compiling, but this is not enough.

**Comment by data-sync-user** [comment]
➤ Beatriz Rizental Machado commented:

Alright, two questions: 1. Are both your branches up to date? I have attempted a clean build on main and then switching to 2.13 branch and was not able to repro the issue. The src/apps/vpn/glean/generated shouldn’t have been generated by either branch in their latest version, so this might be the issue. 2. Do you see logs something like Generating /home/brizental/Projects/mozilla-vpn-client/src/apps/vpn/glean/generated/pings.h from /home/brizental/Projects/mozilla-vpn-client/glean/pings.yaml when you attempt the build again in the 2.13 branch? This is what generated the files the error says are missing.

**Comment by fvalenduc** [comment]
I see that when compilation of the 2.13 branch fails:

warning: `vpnglean` (lib) generated 50 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 4m 15s
[ 31%] Built target vpnglean_builder
[ 31%] Automatic MOC and UIC for target mozillavpn
AutoGen warning: "SRC:/src/apps/vpn/glean/generated/metrics.h" is empty.

AutoGen warning: "SRC:/src/apps/vpn/glean/generated/pings.h" is empty.

This doesn't seem to occur anymore with the 2.14 branch or the main branch. If I remove these two files and restart the build afterwards, compilation ends correctly.
