### PR TITLE
Add BuildID

### LINKED ISSUE #511: Let's add the VersionCode or CommitID to the info page.
Since we now have several android builds with 2.0.3 flying around it's kinda hard to check if we're testing the right build.

### PR DESCRIPTION
**Pull request by strseb**
This adds info field for the BuildID if it's available :) 
closes #511 
Screenshot (08 02

### CODE REVIEW

**Review by Steg17 — APPROVED** [review]

**Comment by lesleyjanenorton** [comment]
Sorry for the lag here - this looks great but or some reason when I try to build locally I get this error: 
```
error: use of undeclared identifier 'BUILD_ID'
In file included from ../../../mv/src/platforms/android/androiddatamigration.cpp:8:
../../../mv/src/mozillavpn.h:174:54: error: use of undeclared identifier 'BUILD_ID'
  const QString buildNumber() const { return QString(BUILD_ID); }
                                                     ^

**Comment by bakulf** [comment]
Can we land this PR? I think it's nice to have. To fix the compilation issue, just add `DEFINES += BUILD_ID=\\\"1234\\\"` in `tests/unit/unit.pro`
